services:
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_database &&
             python manage.py migrate &&
             python manage.py collectstatic --no-input --clear &&
             gunicorn TornBuddy.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.production
    depends_on:
      - db
      - cache


  celery:
    build: .
    command: celery -A TornBuddy worker -l info -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - web
      - db
    env_file:
      - ./.env.production

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env.production

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    env_file:
      - ./.env.production

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  cache:
