# Generated by Django 5.1.3 on 2024-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("torn_id", models.IntegerField(unique=True)),
                ("name", models.CharField(default="?", max_length=20)),
                ("status", models.TextField(default="Ok", max_length=20)),
                ("loot_level", models.IntegerField(default="0")),
                ("last_hospital", models.IntegerField(default=28377016, null=True)),
                ("last_update", models.IntegerField(default=28377016, null=True)),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
    ]
