# Generated by Django 5.1.3 on 2024-12-09 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("player", "0003_alter_player_api_key_alter_player_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("torn_id", models.IntegerField()),
                ("name", models.CharField(null=True)),
                ("tag", models.CharField(null=True)),
                ("tag_image", models.CharField(null=True)),
                ("respect", models.IntegerField(default=-1)),
                ("days_old", models.IntegerField(default=-1)),
                ("capacity", models.IntegerField(default=-1)),
                ("members", models.IntegerField(default=-1)),
                ("enlisted", models.BooleanField(default=False)),
                ("rank_level", models.IntegerField(default=-1)),
                ("rank_name", models.CharField(null=True)),
                ("rank_division", models.IntegerField(default=-1)),
                ("rank_position", models.IntegerField(default=-1)),
                ("rank_wins", models.IntegerField(default=-1)),
                ("best_chain", models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="FactionMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(null=True)),
                ("days_in_faction", models.IntegerField(default=-1)),
                (
                    "faction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faction.faction",
                    ),
                ),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="player.player"
                    ),
                ),
            ],
        ),
    ]
