# Generated by Django 5.1.3 on 2024-12-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="key_level",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="player",
            name="valid_key",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="awards",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="donator",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="enemies",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="forum_posts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="friends",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="karma",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="life_current",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="life_increment",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="life_interval",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="life_maximum",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="property_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="revivable",
            field=models.IntegerField(default=0),
        ),
    ]
