# Generated by Django 5.1.3 on 2024-12-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_player_key_level_player_valid_key_alter_player_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="api_key",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="gender",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="honor",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_action_relative",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_action_status",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="profile_image",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="property",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="role",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="status_color",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="status_description",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="status_details",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="status_state",
            field=models.CharField(),
        ),
    ]
